### ISSUE TITLE
I failed to use this script

### ISSUE THREAD

**Issue by Songs-YZS** [blkph0x/CVE_2024_30078_POC_WIFI#2]
it seems that my ssid  gave a length of 10*255 and it did not cause theWindows 10 22H2 exception to occur。
Can you give a specific example?
Sending Beacon frame with SSID chunk 1/10 of length: 255
....................................................................................................
Sent 100 packets.
Sending Beacon frame with SSID chunk 2/10 of length: 255
....................................................................................................
Sent 100 packets.
Sending Beacon frame with SSID chunk 3/10 of length: 255
....................................................................................................
Sent 100 packets.
Sending Beacon frame with SSID chunk 4/10 of length: 255
....................................................................................................
Sent 100 packets.
Sending Beacon frame with SSID chunk 5/10 of length: 255
....................................................................................................
Sent 100 packets.
Sending Beacon frame with SSID chunk 6/10 of length: 255
....................................................................................................
Sent 100 packets.
Sending Beacon frame with SSID chunk 7/10 of length: 255
....................................................................................................
Sent 100 packets.
Sending Beacon frame with SSID chunk 8/10 of length: 255
....................................................................................................
Sent 100 packets.
Sending Beacon frame with SSID chunk 9/10 of length: 255
....................................................................................................
Sent 100 packets.
Sending Beacon frame with SSID chunk 10/10 of length: 95

**Comment by curry0806** [comment]
Thanks to the author, I also want to know how to use this script successfully
