### ISSUE TITLE
Unable to reproduce on Windows 11 22H2

### ISSUE THREAD

**Issue by lozaning** [blkph0x/CVE_2024_30078_POC_WIFI#5]
Firstly I wanna say that I appreciate you sharing!

I've modified the python code you've provided such that I can get test SSID less than 32 characters long to show up in the wifi tab on the target laptop running unpatched Windows 11 22H2, and ones longer than 32 do not, which I understand to be the proper observed behavior. I've never actually observed the crash though. 

I've tried modifying the number of times each chunk is sent, fiddled with MAC addresses (are mac2 and 3 supposed to match? Should the last octet actually increment with each new chunk?) the length of the SSID, as well as modifying the security type, and the delay between resending packets for each chunk, even tried it on an unpatched Windows 10 laptop, and yet the damn wifi panel persists and functions normally. 

My ultimate goal is to be able to repo this in my home lab, so that I can build out a detection for https://www.nzyme.org/ and enable orgs to proactively alert when these attacks may be happening. 

If you're at all open to providing more specific parameters (I dont even need code) on how to reproduce the crash you get I'd be extremely grateful, as would everyone running nzyme.

**Comment by farhan1211** [comment]
heyy, can you help me with the changes that needed to be made in order to show the name on the wifi tab, I am trying but the ssid is not showing up on the wifi tab
