### ISSUE TITLE
struct.error: required argument is not an integer

### ISSUE THREAD

**Issue by zhefox** [blkph0x/CVE_2024_30078_POC_WIFI#7]
Exception in thread Thread-1 (send_beacon):
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/scapy/fields.py", line 243, in addfield
    return s + self.struct.pack(self.i2m(pkt, val))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
struct.error: required argument is not an integer

**Comment by blkph0x** [comment]
what file are you working with?

**Comment by blkph0x** [comment]
if the AP try again i just uploaded the latest version now but waiting on FarmPoet his fixed the windows association issue so need to implement that fix soon as i find it out unless i figure it out in the mean time

**Comment by blkph0x** [comment]
we will be moving this to a private repo but any finidngs please just add a issue and we will check it out and implement anything needed

**Comment by zhefox** [comment]
I  used AP_Test.py

**Comment by zhefox** [comment]
After the update it looks normal

**Comment by zhefox** [comment]
but when I try to connect test_ap using win10, it shows unable to connect

**Comment by zhefox** [comment]
At the same time, it cannot cause unpatched win10 to crash

**Comment by blkph0x** [comment]
Yes we are woking on this now well farmpoet has fixed that issue from the last msg i got from him but i think his sleeping time zone diffrence. read the updates on the main page the AP is a means to get an attack to take place you will still need to construct the correct data frame to get into the function containing the bug thats the dot11 file but changes will need to take place we are moving this into private and will merge as we get things working.

**Comment by zhefox** [comment]
That's really great. I will also start to analyze how to construct a valid data packet to cause a crash. I didn't look at it carefully before because I was on vacation.I will close this issue,then if I have any progress or updates, I will also send you a private message on x

**Comment by blkph0x** [comment]
I set up a discussion in git just put anything in there
